CRITICAL - 2024-12-18 23:59:28 --> Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in D:\xamppnew\htdocs\projects\veat\system\Debug\Exceptions.php:298
Stack trace:
#0 D:\xamppnew\htdocs\projects\veat\system\Debug\Exceptions.php(298): abs('BAD_REQUEST_ERR...')
#1 D:\xamppnew\htdocs\projects\veat\system\Debug\Exceptions.php(102): CodeIgniter\Debug\Exceptions->determineCodes(Object(Razorpay\Api\Errors\BadRequestError))
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Razorpay\Api\Errors\BadRequestError))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2024-12-18 23:59:57 --> Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in D:\xamppnew\htdocs\projects\veat\system\Debug\Exceptions.php:298
Stack trace:
#0 D:\xamppnew\htdocs\projects\veat\system\Debug\Exceptions.php(298): abs('BAD_REQUEST_ERR...')
#1 D:\xamppnew\htdocs\projects\veat\system\Debug\Exceptions.php(102): CodeIgniter\Debug\Exceptions->determineCodes(Object(Razorpay\Api\Errors\BadRequestError))
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Razorpay\Api\Errors\BadRequestError))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
